name: "dev"
port: "8080"
alarm_email: ""
log_level: "debug" # enum = [debug, info]

mysql:
  user: "root"
  password: "1234"
  host: "localhost"
  port: "3306"
  database: "GoCodeStyle"
  max_conn: 8 # 因為我本地端架設, 電腦只有 8 核心, 以資料庫伺服器的 cpu 核心數為主要依據
  max_idle_conn: 2
